#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.151.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2022-10-12T13-26-30.170693000Z--1f0696781b885e4b3972bb6e0e58d41209aaef0f /root/.ethereum/keystore/
[ ! -e "/root/.ethereum/geth/bootkey" ] && bootnode -genkey /root/.ethereum/geth/bootkey
echo "enode://$(bootnode -nodekey /root/.ethereum/geth/bootkey -writeaddress)@10.151.0.73:30301" > /tmp/eth-enode-url
bootnode -nodekey /root/.ethereum/geth/bootkey -verbosity 9 -addr 10.151.0.73:30301 2> /tmp/bootnode-logs &
python3 -m http.server 8088 -d /tmp &
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
geth --datadir /root/.ethereum --identity="NODE_6" --networkid=10 --syncmode full --snapshot=False --verbosity=2 --allow-insecure-unlock --port 30303 --bootnodes "$(cat /tmp/eth-node-urls)" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique,engine --unlock "0x1f0696781B885e4B3972bB6e0e58d41209aAEf0f" --password "/tmp/eth-password"  &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

