# For docker
# 新版docker compose 不在是docker-compose 命令
alias dcbuild='docker compose build'
alias dcup='docker compose up'
alias dcdown='docker compose down'
alias dockps='docker ps --format "{{.ID}}  {{.Names}}" | sort -k 2'
docksh() { docker exec -it $1 /bin/bash; }


# Misc. 
alias ll='ls -l'
